### ISSUE TITLE
Missing some words

### ISSUE THREAD

**Issue by romainrichard** [git-pull/tao-of-tmux#16]
At https://github.com/git-pull/tao-of-tmux/blame/master/manuscript/11-tips-and-tricks.md#L241, we can read:
```
# verify tmuxp is installed, if not you to fix your `PATH`
```
Something is missing in that second part.

**Comment by romainrichard** [comment]
I don't think the fix addresses the raised issue:
```
if not you to fix your `PATH`
```
is not (AFAICT) English.
I would imagine it should be something like:
```
if not fix your `PATH`
```
or
```
if not you should fix your `PATH`
```

**Comment by tony** [comment]
you're right

**Comment by tony** [comment]
try now https://leanpub.com/the-tao-of-tmux/read

**Comment by romainrichard** [comment]
lgtm
